import { Arrow, Label } from './Scenes';

export default function Connector(){
 return <div className="v3-page is-flow connector-page"><header className="main-header wrap"><a href="/" aria-label="Nexa home"><img src="/nexa-white.png" width="128" height="28" alt="Nexa"/></a><a href="/">Back to homepage ↗</a></header><main>
 <section className="connector-intro wrap section-pad"><Label>NEXA AI CONNECTOR / ONE CONNECTION</Label><h1>Your property.<br/><em>Ready to answer.</em></h1><p>For hotels and vacation rentals. Your live availability, final prices and direct booking route, available to the AI your next guest already uses.</p><a className="button button-dark" href="/#watch-a-booking">Watch a booking happen <Arrow/></a></section>
 <section className="connector-doors wrap"><article><small>01 / NEXA DIRECT</small><h2>They ask for you.</h2><blockquote>“Find me a room at your hotel.”</blockquote><p>A guest names your property or brand. Give their AI the details it needs to recommend a booking on your own website.</p></article><article><small>02 / NEXA AGENT</small><h2>They ask for a stay.</h2><blockquote>“Find me a place near the sea.”</blockquote><p>A guest starts with a destination. Make your property available as a named recommendation, with a final price and a direct way to book.</p></article></section>
 <section className="connector-explainer wrap section-pad"><Label>YOUR EXISTING PMS / YOUR OWN WEBSITE</Label><h2>One connection.<br/><em>Both conversations.</em></h2><p>NEXA connects through the PMS you already run. Your website remains the booking destination, and reservations arrive in your PMS like any direct booking.</p><div className="connector-pms">{['Guesty','Hostaway','BoomNow','Hospitable','Rentals United','HotelSync'].map(name=><span key={name}>{name}</span>)}</div><div className="connector-ownership"><h3>Your guest. Your terms. Your payment.</h3><p>The guest installs nothing. No application, plugin or activation is needed in their chat. Booking and payment complete on your website, under your terms. NEXA never holds the guest's money and is not a party to the reservation.</p></div><a href="/#get-priced" className="button button-dark">Get Priced <Arrow diagonal/></a></section>
 </main></div>;
}
